### Listado de etiquetas de john_doe
GET http://localhost:9999/api/v1/labels
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsInR5cGUiOiJBVVRIIiwiZXhwIjoxNjk2NzE3MTUzLCJ1c2VySWQiOjF9.sgUh51rd0ArT7dtjjW40nbAN6k043HnvlBj7-4k4Rjw
Accept: application/json
Content-Type: application/json

### Creación de una etiqueta
POST http://localhost:9999/api/v1/labels
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsInR5cGUiOiJBVVRIIiwiZXhwIjoxNjk2NzE3MTUzLCJ1c2VySWQiOjF9.sgUh51rd0ArT7dtjjW40nbAN6k043HnvlBj7-4k4Rjw
Accept: application/json
Content-Type: application/json

{
  "labelName": "Colegio",
  "userId": 1
}

### Modificación de una etiqueta
PUT http://localhost:9999/api/v1/labels/17
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsInR5cGUiOiJBVVRIIiwiZXhwIjoxNjk2NzE3MTUzLCJ1c2VySWQiOjF9.sgUh51rd0ArT7dtjjW40nbAN6k043HnvlBj7-4k4Rjw
Accept: application/json
Content-Type: application/json

{
  "labelName": "Universidad"
}

### Eliminación de una etiqueta
DELETE http://localhost:9999/api/v1/labels/17
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsInR5cGUiOiJBVVRIIiwiZXhwIjoxNjk2NzE3MTUzLCJ1c2VySWQiOjF9.sgUh51rd0ArT7dtjjW40nbAN6k043HnvlBj7-4k4Rjw
Accept: application/json
Content-Type: application/json
