### Listado de etiquetas de john_doe
GET http://localhost:9999/api/v1/labels
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsInR5cGUiOiJBVVRIIiwiZXhwIjoxNjk2NzA2MDMxLCJ1c2VySWQiOjF9.ISizCCZlm3WZ8CkYefghnQGLe2AIjFqMKCw0N81WXlU

### Creación de una etiqueta
POST http://localhost:9999/api/v1/labels
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsInR5cGUiOiJBVVRIIiwiZXhwIjoxNjk2NzA2MDMxLCJ1c2VySWQiOjF9.ISizCCZlm3WZ8CkYefghnQGLe2AIjFqMKCw0N81WXlU
Accept: application/json
Content-Type: application/json

{
  "labelName": "Colegio",
  "userId": 1
}

### Modificación de una etiqueta
PUT http://localhost:9999/api/v1/labels/15
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsInR5cGUiOiJBVVRIIiwiZXhwIjoxNjk2NzA2MDMxLCJ1c2VySWQiOjF9.ISizCCZlm3WZ8CkYefghnQGLe2AIjFqMKCw0N81WXlU
Accept: application/json
Content-Type: application/json

{
  "labelName": "Universidad"
}

### Eliminación de una etiqueta
DELETE http://localhost:9999/api/v1/labels/15
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsInR5cGUiOiJBVVRIIiwiZXhwIjoxNjk2NzA2MDMxLCJ1c2VySWQiOjF9.ISizCCZlm3WZ8CkYefghnQGLe2AIjFqMKCw0N81WXlU
