### Login exitoso
POST http://localhost:9999/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
    "username" : "john_doe",
    "password" : "password123"
}

### Login fallido
POST http://localhost:9999/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "username" : "john_doe",
  "password" : "password456"
}

### Login exitoso / previa inserción por SQL
POST http://localhost:9999/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "username" : "sarah_smith",
  "password" : "password987"
}
